CREATE TABLE IF NOT EXISTS quote_bot_shanwords (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(100) NOT NULL,
    definition TEXT NOT NULL,
    added_by_user_id VARCHAR(32) DEFAULT NULL,
    added_by_username VARCHAR(100) DEFAULT NULL,
    used_in_daily_cycle TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uniq_word (word)
);

INSERT INTO quote_bot_shanwords (word, definition, used_in_daily_cycle) VALUES
('Shabandoned', 'When Shannyn finally abandons us.', 0),
('Shannafied', 'To make something in a Shannyn style.', 0),
('Shannynstic', 'A pure, unfiltered Shannyn experience.', 0),
('Shanchanted', 'Enchanted by Shannyn''s presence.', 0),
('Shantastic', 'Something impressively Shannyn-like; better than fantastic.', 0),
('Shanicked', 'The panic that sets in right before Shannyn shows up.', 0),
('Shannihilate', 'To completely wreck a plan the way Shannyn always does.', 0),
('Shanolatry', 'The borderline-worship of Shannyn by the group chat.', 0),
('Shanchor', 'The one thing keeping the friend group grounded: Shannyn.', 0),
('Shandemic', 'When Shannyn''s chaos spreads to everyone in the room.', 0),
('Shanarchy', 'Total chaos caused directly by Shannyn.', 0),
('Shantagonize', 'To purposely annoy Shannyn for entertainment.', 0),
('Shanticipate', 'The nervous excitement of waiting for Shannyn to arrive (late).', 0),
('Shanquility', 'The rare, peaceful calm right after Shannyn leaves.', 0),
('Shannoyed', 'The specific irritation only Shannyn can cause.', 0),
('Shanhattan', 'The amount of space Shannyn''s stuff takes up in a room.', 0),
('Shanigans', 'Shenanigans, but worse, because Shannyn''s involved.', 0),
('Shansanity', 'The state of mind after too much time with Shannyn.', 0),
('Shandwich', 'Getting stuck in the middle of one of Shannyn''s arguments.', 0),
('Shanquished', 'Utterly defeated by Shannyn in literally anything.', 0),
('Shantidote', 'The only cure for a bad mood: more Shannyn.', 0),
('Shanvasion', 'When Shannyn takes over a conversation entirely.', 0),
('Shanfamous', 'Shannyn''s reputation preceding her into a room.', 0),
('Shanundrum', 'A confusing situation only Shannyn could create.', 0),
('Shanology', 'The ongoing group study of why Shannyn does what she does.', 0),
('Shanterrogate', 'To grill Shannyn with questions about her whereabouts.', 0),
('Shantourage', 'The group of people Shannyn somehow always has following her.', 0),
('Shanthem', 'The one song Shannyn will not stop playing.', 0),
('Shanigma', 'The unsolvable mystery of what Shannyn is thinking.', 0),
('Shanpocalypse', 'The end result of Shannyn being left unsupervised.', 0),
('Shanction', 'The punishment for doing something without consulting Shannyn first.', 0),
('Shandom', 'The completely unpredictable thing Shannyn does next.', 0),
('Shanecdote', 'A story about Shannyn that somehow gets told every single time.', 0),
('Shantrance', 'The daze everyone falls into listening to Shannyn talk.', 0),
('Shanalyze', 'To overthink literally everything Shannyn says.', 0),
('Shanquest', 'The group''s mission to find Shannyn after she disappears.', 0),
('Shanguard', 'Whoever has to keep an eye on Shannyn at a party.', 0),
('Shanterference', 'Shannyn getting involved in something that isn''t her business.', 0),
('Shanfiltrate', 'To sneak into a conversation the way Shannyn always does.', 0),
('Shanticlimactic', 'When Shannyn''s big story ends up going nowhere.', 0),
('Shanovate', 'To come up with a new, slightly unhinged plan, Shannyn-style.', 0),
('Shanomenon', 'A strange event that can only be explained by Shannyn.', 0),
('Shanstitute', 'Whoever has to fill in when Shannyn''s not around (badly).', 0),
('Shanterval', 'The short window of peace between bouts of Shannyn''s chaos.', 0),
('Shansomnia', 'Staying up too late because Shannyn wouldn''t stop texting.', 0),
('Shancestor', 'The person who taught Shannyn to be like this in the first place.', 0),
('Shanvincible', 'Shannyn''s unshakeable confidence, no matter the situation.', 0),
('Shandalous', 'Something scandalous, but specifically because Shannyn did it.', 0),
('Shanteraction', 'Any interaction with Shannyn that leaves you slightly confused.', 0),
('Shanticipointment', 'The letdown after hyping up a Shannyn story that flops.', 0),
('Shanabolic', 'The burst of chaotic energy Shannyn brings into any room.', 0),
('Shantidepressant', 'The mood boost from a Shannyn text arriving at the right time.', 0),
('Shanlightenment', 'The moment you finally understand a Shannyn reference.', 0),
('Shanhole', 'The black hole of time that is any conversation with Shannyn.', 0),
('Shantidisestablishmentarianism', 'The deeply held, oddly specific opinion Shannyn refuses to back down from.', 0),
('Shanquisition', 'The group interrogation that happens whenever Shannyn shows up late.', 0),
('Shanvelope', 'Whatever chaotic energy Shannyn wraps around an otherwise normal plan.', 0),
('Shantasize', 'To imagine an event going way smoother than it will, out of sheer Shannyn-brand optimism.', 0),
('Shanophobia', 'The mild dread of finding out what Shannyn''s about to say next.', 0),
('Shanospace', 'The amount of group-chat scrolling required to catch up on Shannyn''s latest saga.', 0),
('Shanchant', 'The phrase the group says in unison whenever Shannyn does something painfully on-brand, like that''s so Shannyn.', 0),
('Shanvest', 'To fully commit to a ridiculous plan just because Shannyn proposed it.', 0),
('Shanteract', 'To attempt, and fail, to talk Shannyn out of something.', 0),
('Shanpire', 'Someone who drains all the energy from a hangout, in the specific way only Shannyn can.', 0),
('Shanquake', 'The disruption felt across the group chat the second Shannyn posts something unhinged.', 0),
('Shanwave', 'The ripple effect of Shannyn''s mood spreading to everyone in the room.', 0),
('Shanoxious', 'Mildly obnoxious, but in the lovable way that''s uniquely Shannyn.', 0),
('Shanteroid', 'A random, out-of-nowhere comment from Shannyn that derails the entire conversation.', 0),
('Shantennae', 'The sixth sense that warns you Shannyn is about to say something wild.', 0),
('Shanvious', 'Suspicious behavior that, nine times out of ten, turns out to be Shannyn.', 0),
('Shanthropy', 'Shannyn''s rare, generous gestures, always with a small catch attached.', 0),
('Shansterpiece', 'Any story Shannyn tells that somehow gets longer and more dramatic every retelling.', 0),
('Shanverse', 'The alternate reality Shannyn seems to live in, parallel to everyone else''s.', 0),
('Shanchise', 'The running bit about Shannyn that the group refuses to retire.', 0),
('Shanvasive', 'How quickly Shannyn''s opinion ends up taking over a group decision.', 0),
('Shanalog', 'Doing something the old-fashioned way because Shannyn still won''t check the group chat.', 0),
('Shantagious', 'How fast Shannyn''s laugh spreads to everyone nearby.', 0),
('Shanfection', 'The oddly specific thing Shannyn is completely obsessed with this week.', 0),
('Shanterlude', 'The brief moment of calm before Shannyn starts a new bit.', 0),
('Shancore', 'The unmistakable aesthetic and vibe that can only be described as Shannyn.', 0),
('Shanquisitive', 'Asking far too many questions, Shannyn-style.', 0),
('Shanverted', 'Talked into doing the exact thing you swore you wouldn''t, because Shannyn asked nicely.', 0),
('Shanterrupt', 'To cut into a conversation mid-sentence, a Shannyn signature move.', 0),
('Shanticize', 'To gently mock something, which Shannyn will inevitably do anyway.', 0),
('Shandshake', 'The fragile, temporary truce that follows an argument with Shannyn.', 0),
('Shanteful', 'The specific relief and gratitude felt when Shannyn actually shows up on time.', 0),
('Shanquire', 'To casually ask Shannyn for a small favor, knowing it will become a full ordeal.', 0),
('Shansterious', 'Deliberately vague about her plans, a very Shannyn trait.', 0),
('Shanolithic', 'A Shannyn story so long and immovable it takes over an entire hangout.', 0),
('Shanumeral', 'The running, wildly unreliable tally of how many times Shannyn has canceled plans.', 0),
('Shanbush', 'To be completely blindsided by a Shannyn remark.', 0),
('Shanterrific', 'Genuinely great, but only because Shannyn happened to be there.', 0),
('Shanquil', 'Suspiciously calm right before Shannyn causes total chaos.', 0),
('Shanuscript', 'The increasingly long text Shannyn sends to explain a five-minute story.', 0),
('Shanthusiasm', 'Shannyn''s completely over-the-top excitement about something totally mundane.', 0),
('Shanterprise', 'Whatever questionable new business idea Shannyn is pitching this month.', 0),
('Shancellation', 'The last-minute plan change that is, somehow, always Shannyn''s doing.', 0),
('Shanomaly', 'Something so strange it can only be explained by Shannyn being involved.', 0),
('Shanuary', 'The brief period after New Year''s when Shannyn insists she''s changed.', 0),
('Shanticular', 'Overly specific about one tiny detail nobody else cares about, peak Shannyn.', 0),
('Shanescence', 'The glow-up era Shannyn insists she is currently in.', 0),
('Shantour', 'The unnecessarily long detour Shannyn insists the group take.', 0),
('Shanniversary', 'The informally agreed-upon (but never real) anniversary of the last time Shannyn was on time.', 0);
